name: Build

on:
  workflow_call:
  push:
    branches:
      - trunk
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildExtensionBundle:
    name: Build extension bundle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@da5279aa4d76745ef32970e49b5ef7903a3b457a # v2.2.2
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@da5279aa4d76745ef32970e49b5ef7903a3b457a # v2.2.2
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      - name: Publish dev build to GitHub
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        uses: woocommerce/grow/publish-extension-dev-build@da5279aa4d76745ef32970e49b5ef7903a3b457a # v2.2.2
        with:
          extension-asset-path: reddit-for-woocommerce.zip

      - name: Publish build artifact
        if: ${{ ! ( github.event_name == 'push' && github.ref_name == 'develop' ) }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: reddit-for-woocommerce.zip
          path: ${{ github.workspace }}/reddit-for-woocommerce.zip
          # Do not bloat the storage. Keep in only long enough for a caller workflow to pick it up and follow up with some manual debugging.
          retention-days: 2
