name: JavaScript Unit Tests

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.js"
      - package.json
      - package-lock.json
      - .github/workflows/js-unit-tests.yml
  pull_request:
    paths:
      - "**.js"
      - package.json
      - package-lock.json
      - .github/workflows/js-unit-tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  UnitTests:
    name: JavaScript unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@da5279aa4d76745ef32970e49b5ef7903a3b457a # v2.2.2
        with:
          node-version-file: ".nvmrc"

      - name: Run JavaScript unit tests
        run: npm run test:js

      - name: Upload JS unit coverage report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/clover.xml
          flags: js-unit-tests
          name: js-coverage-report
